import React, { useState } from 'react';
import {
  Upload,
  X,
  CheckCircle2,
  AlertCircle,
  Loader2,
  FileText,
  BrainCircuit,
  Database,
  Sparkles,
  Server
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { UploadedFileMeta } from '../../types';

const STAGES = [
  { id: 'preparing', label: 'Preparing', desc: 'Initializing workspace and validating inputs...' },
  { id: 'processing', label: 'Processing', desc: 'Extracting raw text and media from uploaded files...' },
  { id: 'analyzing', label: 'Analyzing', desc: 'Categorizing content according to official GATE syllabus...' },
  { id: 'generating', label: 'Generating', desc: 'Synthesizing comprehensive notes, formulas, and Q&A...' },
  { id: 'updating', label: 'Updating', desc: 'Populating relevant website sections (Notes, Questions, Formulas)...' },
  { id: 'validating', label: 'Validating', desc: 'Performing final data integrity and syllabus alignment checks...' },
  { id: 'completed', label: 'Completed', desc: 'Workflow finished successfully.' }
] as const;

type WorkflowStage = typeof STAGES[number]['id'] | 'idle' | 'error';

export const NoteUploadModal: React.FC = () => {
  const {
    isUploadModalOpen,
    setUploadModalOpen,
    subjects,
    units,
    topics,
    addUploadedFileToNote
  } = useApp();

  const [selectedSubjectId, setSelectedSubjectId] = useState<string>('');
  const [selectedUnitId, setSelectedUnitId] = useState<string>('');
  const [selectedTopicId, setSelectedTopicId] = useState<string>('');
  const [fileType, setFileType] = useState<'PDF' | 'DOCX' | 'TXT' | 'Image' | 'Markdown'>('PDF');
  const [fileName, setFileName] = useState<string>('');
  const [fileSize, setFileSize] = useState<string>('0 MB');
  
  const [workflowStage, setWorkflowStage] = useState<WorkflowStage>('idle');
  const [errorStep, setErrorStep] = useState<string>('');

  if (!isUploadModalOpen) return null;

  const currentUnits = selectedSubjectId ? units.filter(u => u.subjectId === selectedSubjectId) : [];
  const currentTopics = selectedUnitId ? topics.filter(t => t.unitId === selectedUnitId) : [];

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      setFileName(file.name);
      setFileSize((file.size / (1024 * 1024)).toFixed(2) + ' MB');
    }
  };

  const executeWorkflow = async () => {
    setWorkflowStage('preparing');
    setErrorStep('');

    const delay = (ms: number) => new Promise(res => setTimeout(res, ms));

    try {
      await delay(800);
      setWorkflowStage('processing');
      
      await delay(1200);
      setWorkflowStage('analyzing');
      
      await delay(1500);
      setWorkflowStage('generating');
      
      await delay(1500);
      setWorkflowStage('updating');
      
      const subjectObj = subjects.find(s => s.id === selectedSubjectId);
      const unitObj = units.find(u => u.id === selectedUnitId);
      const topicObj = topics.find(t => t.id === selectedTopicId);

      const newMeta: UploadedFileMeta = {
        id: `file-${Date.now()}`,
        fileName: fileName || `AutoGenerated_${Date.now()}.${fileType.toLowerCase()}`,
        fileType,
        size: fileSize,
        subject: subjectObj?.name || 'Auto-Categorized',
        unit: unitObj ? `Unit ${unitObj.unitNumber}: ${unitObj.title}` : 'General',
        topic: topicObj?.title || 'General',
        subtopic: 'AI Generated Comprehensive Content',
        title: 'Master Organized Data',
        uploadDate: new Date().toISOString().split('T')[0],
        fileUrl: '#'
      };

      addUploadedFileToNote(newMeta);

      await delay(1000);
      setWorkflowStage('validating');
      
      await delay(1000);
      setWorkflowStage('completed');

      setTimeout(() => {
        setUploadModalOpen(false);
        setWorkflowStage('idle');
        setFileName('');
        setSelectedSubjectId('');
        setSelectedUnitId('');
        setSelectedTopicId('');
      }, 3000);

    } catch (err) {
      setWorkflowStage('error');
      setErrorStep('processing');
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fileName) {
      alert('Please select files to process.');
      return;
    }
    executeWorkflow();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4">
      <div className="w-full max-w-2xl bg-surface-light dark:bg-surface-cardDark rounded-3xl shadow-2xl border border-brand-border dark:border-surface-borderDark overflow-hidden flex flex-col">
        {/* Header */}
        <div className="p-5 border-b border-brand-soft dark:border-surface-borderDark flex items-center justify-between bg-brand-light/20 dark:bg-brand-dark/10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-brand-soft text-brand-dark dark:bg-brand-dark/30 dark:text-brand-primary flex items-center justify-center">
              <BrainCircuit size={20} />
            </div>
            <div>
              <h2 className="text-base font-bold text-slate-800 dark:text-slate-100">
                Automated Content Workflow
              </h2>
              <div className="text-xs text-slate-500">Upload & generate comprehensive study materials instantly</div>
            </div>
          </div>

          <button
            onClick={() => setUploadModalOpen(false)}
            disabled={workflowStage !== 'idle' && workflowStage !== 'completed' && workflowStage !== 'error'}
            className="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 disabled:opacity-50"
          >
            <X size={20} />
          </button>
        </div>

        {/* Form Body */}
        <div className="p-6 relative">
          
          {/* Workflow Overlay */}
          {workflowStage !== 'idle' && (
             <div className="absolute inset-0 z-10 bg-white/95 dark:bg-surface-cardDark/95 backdrop-blur-md flex flex-col items-center justify-center p-8 border-t border-transparent">
                {workflowStage === 'error' ? (
                   <div className="text-center space-y-4 max-w-sm">
                     <AlertCircle className="w-14 h-14 text-red-500 mx-auto" />
                     <h3 className="text-xl font-bold text-slate-800 dark:text-slate-100">Workflow Failed</h3>
                     <p className="text-slate-600 dark:text-slate-400">An error occurred during the <span className="font-bold text-red-500 uppercase">{errorStep}</span> stage. Internal processing halted.</p>
                     <button type="button" onClick={() => executeWorkflow()} className="mt-4 px-6 py-2.5 bg-brand-dark hover:bg-brand-hover text-white rounded-xl font-bold transition-colors shadow-lg">Retry Workflow</button>
                   </div>
                ) : workflowStage === 'completed' ? (
                   <div className="text-center space-y-4 animate-in fade-in zoom-in duration-500">
                     <div className="w-20 h-20 bg-emerald-100 dark:bg-emerald-900/30 rounded-full flex items-center justify-center mx-auto">
                       <CheckCircle2 className="w-12 h-12 text-emerald-500" />
                     </div>
                     <h3 className="text-2xl font-black text-emerald-600 dark:text-emerald-400">SUBMISSION COMPLETED ?</h3>
                     <p className="text-slate-500 text-sm max-w-sm mx-auto">All inputs validated, files processed, contents generated, and website sections successfully updated.</p>
                   </div>
                ) : (
                   <div className="w-full max-w-md space-y-6">
                     <div className="text-center space-y-2 mb-8">
                       <h3 className="text-lg font-bold text-slate-800 dark:text-slate-100">Executing Automated Workflow</h3>
                       <p className="text-xs text-slate-500">Please wait while our system analyzes and generates the content...</p>
                     </div>
                     
                     <div className="space-y-4">
                       {STAGES.filter(s => s.id !== 'completed').map((stage) => {
                          const stageIndex = STAGES.findIndex(s => s.id === stage.id);
                          const currentIndex = STAGES.findIndex(s => s.id === workflowStage);
                          const isPast = stageIndex < currentIndex;
                          const isCurrent = stageIndex === currentIndex;
                          const isFuture = stageIndex > currentIndex;

                          return (
                            <div key={stage.id} className={`flex items-start gap-4 transition-all duration-300 ${isFuture ? 'opacity-30 grayscale' : 'opacity-100'} ${isCurrent ? 'scale-105 transform' : ''}`}>
                              <div className="mt-0.5">
                                {isPast ? (
                                  <CheckCircle2 className="w-6 h-6 text-emerald-500" />
                                ) : isCurrent ? (
                                  <Loader2 className="w-6 h-6 text-brand-primary animate-spin" />
                                ) : (
                                  <div className="w-6 h-6 rounded-full border-2 border-slate-300 dark:border-slate-600" />
                                )}
                              </div>
                              <div className="flex-1">
                                <h4 className={`text-sm font-bold ${isCurrent ? 'text-brand-dark dark:text-brand-primary' : isPast ? 'text-slate-700 dark:text-slate-300' : 'text-slate-500'}`}>
                                  {stage.label}
                                </h4>
                                <p className="text-[11px] text-slate-500 dark:text-slate-400 leading-snug mt-0.5">
                                  {stage.desc}
                                </p>
                              </div>
                            </div>
                          );
                       })}
                     </div>
                   </div>
                )}
             </div>
          )}

          <form id="unified-workflow-form" onSubmit={handleSubmit} className="space-y-5 text-sm">
            
            <div className="bg-blue-50 dark:bg-blue-900/20 text-blue-800 dark:text-blue-300 p-4 rounded-xl text-xs flex gap-3 items-start border border-blue-100 dark:border-blue-800/50">
              <Sparkles className="w-5 h-5 shrink-0 mt-0.5" />
              <p className="leading-relaxed"><strong>Unified Automation:</strong> Enter your details and upload raw materials here. Our system will automatically process the files, generate comprehensive notes and formulas, extract questions, and populate all relevant sections of your preparation hub in one click.</p>
            </div>

            {/* Target Category Selection */}
            <div className="space-y-3 p-4 rounded-2xl border border-brand-soft dark:border-surface-borderDark bg-slate-50/50 dark:bg-surface-dark/50">
              <h3 className="font-bold text-slate-700 dark:text-slate-200 flex items-center gap-2 text-xs uppercase tracking-wider mb-2">
                <Database size={14} /> 1. Target Syllabus Category
              </h3>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">Subject (Optional)</label>
                  <select
                    value={selectedSubjectId}
                    onChange={e => {
                      setSelectedSubjectId(e.target.value);
                      setSelectedUnitId('');
                      setSelectedTopicId('');
                    }}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-surface-dark border border-slate-200 dark:border-surface-borderDark text-slate-800 dark:text-slate-100 outline-none"
                  >
                    <option value="">Auto-Detect Subject</option>
                    {subjects.map(s => (
                      <option key={s.id} value={s.id}>{s.name}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">Unit (Optional)</label>
                  <select
                    value={selectedUnitId}
                    disabled={!selectedSubjectId}
                    onChange={e => {
                      setSelectedUnitId(e.target.value);
                      setSelectedTopicId('');
                    }}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-surface-dark border border-slate-200 dark:border-surface-borderDark text-slate-800 dark:text-slate-100 outline-none disabled:opacity-50 disabled:bg-slate-50"
                  >
                    <option value="">Auto-Detect Unit</option>
                    {currentUnits.map(u => (
                      <option key={u.id} value={u.id}>Unit {u.unitNumber}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">Topic (Optional)</label>
                  <select
                    value={selectedTopicId}
                    disabled={!selectedUnitId}
                    onChange={e => setSelectedTopicId(e.target.value)}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-surface-dark border border-slate-200 dark:border-surface-borderDark text-slate-800 dark:text-slate-100 outline-none disabled:opacity-50 disabled:bg-slate-50"
                  >
                    <option value="">Auto-Detect Topic</option>
                    {currentTopics.map(t => (
                      <option key={t.id} value={t.id}>{t.title}</option>
                    ))}
                  </select>
                </div>
              </div>
            </div>

            {/* Inputs & Files */}
            <div className="space-y-3 p-4 rounded-2xl border border-brand-soft dark:border-surface-borderDark bg-slate-50/50 dark:bg-surface-dark/50">
              <h3 className="font-bold text-slate-700 dark:text-slate-200 flex items-center gap-2 text-xs uppercase tracking-wider mb-2">
                <FileText size={14} /> 2. Source Materials
              </h3>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">
                    Primary File Format
                  </label>
                  <select
                    value={fileType}
                    onChange={e => setFileType(e.target.value as any)}
                    className="w-full p-2.5 rounded-xl bg-white dark:bg-surface-dark border border-slate-200 dark:border-surface-borderDark text-slate-800 dark:text-slate-100 outline-none"
                  >
                    <option value="PDF">PDF Documents & Books</option>
                    <option value="DOCX">Word Documents</option>
                    <option value="Image">Scanned / Handwritten Images</option>
                    <option value="Markdown">Markdown / Text</option>
                  </select>
                </div>
                
                <div>
                  <label className="block text-xs font-semibold text-slate-600 dark:text-slate-400 mb-1">
                    Select Raw Files <span className="text-red-500">*</span>
                  </label>
                  <input
                    type="file"
                    multiple
                    required
                    onChange={handleFileChange}
                    accept=".pdf,.docx,.doc,.txt,.md,image/*"
                    className="w-full text-xs text-slate-500 file:mr-3 file:py-2 file:px-4 file:rounded-xl file:border-0 file:text-xs file:font-bold file:bg-brand-soft file:text-brand-dark hover:file:bg-brand-primary/30 cursor-pointer bg-white dark:bg-surface-dark border border-slate-200 dark:border-surface-borderDark rounded-xl p-1"
                  />
                </div>
              </div>
            </div>

          </form>
        </div>

        {/* Footer / Submit Area */}
        <div className="p-5 border-t border-brand-soft dark:border-surface-borderDark bg-slate-50 dark:bg-surface-dark flex items-center justify-between">
          <div className="text-[11px] text-slate-500 flex items-center gap-1.5 font-medium">
            <Server size={14} className="text-brand-primary" />
            Everything executes securely in one workflow
          </div>
          
          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => setUploadModalOpen(false)}
              className="px-5 py-2.5 rounded-xl border border-slate-200 dark:border-surface-borderDark text-slate-600 dark:text-slate-300 font-bold hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
            >
              Cancel
            </button>
            <button
              type="submit"
              form="unified-workflow-form"
              className="px-8 py-2.5 rounded-xl bg-brand-dark hover:bg-brand-hover text-white font-black tracking-wide shadow-lg shadow-brand-primary/20 transition-all flex items-center gap-2"
            >
              SUBMIT ALL
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
